version: '3'
networks:
  app-network: null
services:
  nginx:
    container_name: 'nginx_${APP_NAME}'
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www/project
      - ./nginx/log:/var/log/nginx
    tty: true
    networks:
      - app-network
  redis:
    container_name: 'redis_${APP_NAME}'
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      - app-network
  mysql:
    container_name: 'mysql_${APP_NAME}'
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    ports:
      - "43306:3306"
    environment:
      MYSQL_DATABASE: football
      MYSQL_USER: user      
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root@secret123
    networks:
      - app-network
  node:
    container_name: 'node_${APP_NAME}'
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - '../fe:/usr/src/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    networks:
      - app-network